### ISSUE TITLE
Add `cast` helper

### ISSUE THREAD

**Issue by aleclarson** [alloc/tusken#3]
This creates an `Expression` object that renders the `CAST ... AS` operator.

```ts
cast(20, t.text)
```

This will require an `export const` statement for each type in the `t` namespace, as there needs to be a way to infer the identifier that trails the `AS` operator when building the query at runtime.

**Comment by harishfalco** [comment]
Greetings, @aleclarson 
 I'm new to contributing to open-source, I'd want to fix this problem. Give it to me, if possible.

**Comment by aleclarson** [comment]
Welcome, @harishfalco!
The typical way to contribute is by trying to implement the feature alone, without guidance. If you ever get stuck on understanding how the internals work, you can open a new issue with your questions. Once you have the feature working locally, it's time to submit a pull request so I can review your work. Good luck!

**Comment by aleclarson** [comment]
Closing in favor of #14
